### ISSUE TITLE
dolphin 環境構築手順

### ISSUE THREAD

**Issue by t-iwano** [axsh/wakame-dolphin#11]
新規でdolphinの環境を構築するために手順と正常性を確認するための手順を構築する。

**Comment by t-iwano** [comment]
環境にあらかじめgitの設定をしておくこと

``` bash
[vagrant@dolphin ~]$ git clone https://github.com/axsh/wakame-dolphin
Initialized empty Git repository in /home/vagrant/wakame-dolphin/.git/
remote: Counting objects: 1871, done.
remote: Compressing objects: 100% (871/871), done.
remote: Total 1871 (delta 923), reused 1859 (delta 919)
Receiving objects: 100% (1871/1871), 194.16 KiB | 208 KiB/s, done.
Resolving deltas: 100% (923/923), done.
[vagrant@dolphin ~]$ ls
wakame-dolphin
[vagrant@dolphin ~]$ wakame-dolphin/
-bash: wakame-dolphin/: is a directory
[vagrant@dolphin ~]$ cd wakame-dolphin/
[vagrant@dolphin wakame-dolphin]$ ls
Gemfile  Makefile  README.md  Rakefile  bin  config  lib  script  spec  templates  tests  wakame-dolphin.gemspec
[vagrant@dolphin wakame-dolphin]$ which make
/usr/bin/make
[vagrant@dolphin wakame-dolphin]$ less Makefile
```

makeコマンドを実行し環境を構築する。

``` bash
[vagrant@dolphin wakame-dolphin]$ make dev
/home/vagrant/wakame-dolphin/deployment/rubybuild/build_ruby.sh
make: /home/vagrant/wakame-dolphin/deployment/rubybuild/build_ruby.sh: Command not found
make: *** [build-ruby] Error 127
```

build_rubyコマンドはbranch fix-0.0.5にしかないためbranchを切り替える

``` bash
[vagrant@dolphin wakame-dolphin]$ git branch
* master
[vagrant@dolphin wakame-dolphin]$ git checkout fix-0.0.5
Branch fix-0.0.5 set up to track remote branch fix-0.0.5 from origin.
Switched to a new branch 'fix-0.0.5'
[vagrant@dolphin wakame-dolphin]$ git branch
* fix-0.0.5
  master
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
makeしたら関連パッケージがないと怒られた。

``` bash
[vagrant@dolphin wakame-dolphin]$ sudo make dev
/home/vagrant/wakame-dolphin/deployment/rubybuild/build_ruby.sh
Missing dependencies.
Make sure all of the following are installed:
make git gcc gcc-c++ zlib-devel openssl-devel mysql-devel sqlite-devel
make: *** [build-ruby] Error 1
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
関連パッケージを追加

``` bash
[vagrant@dolphin wakame-dolphin]$ sudo yum install make git gcc gcc-c++ zlib-devel openssl-devel mysql-devel sqlite-devel
```

**Comment by t-iwano** [comment]
再度make実行

``` bash
sudo make dev
```

**Comment by t-iwano** [comment]
PATHの設定

``` bash
[vagrant@dolphin wakame-dolphin]$ PATH=$PATH:~/wakame-dolphin/ruby/bin
```

**Comment by t-iwano** [comment]
mysqlのインストール

``` bash
[vagrant@dolphin wakame-dolphin]$ sudo yum install mysql-server
```

**Comment by t-iwano** [comment]
configファイルのコピー

``` bash
[vagrant@dolphin wakame-dolphin]$ cp config/dolphin-mysql.conf.travis config/dolphin.conf
[vagrant@dolphin wakame-dolphin]$ less config/dolphin.conf
```

初期データ投入

``` bash
[vagrant@dolphin wakame-dolphin]$ mysql -u root -e 'create database dolphin;'
[vagrant@dolphin wakame-dolphin]$ bundle exec rake db:mysql:init
```

**Comment by t-iwano** [comment]
実行するとエラー

``` bash
[vagrant@dolphin wakame-dolphin]$ bundle exec ./bin/dolphin_server
/home/vagrant/wakame-dolphin/vendor/bundle/ruby/2.0.0/bundler/gems/reel-rack-a44e3629d003/lib/reel/rack/server.rb:8: warning: toplevel constant HTTP referenced by Reel::Server::HTTP
D, [2014-03-18T18:26:48.355945 #27682] DEBUG -- : Terminating 4 actors...
/home/vagrant/wakame-dolphin/vendor/bundle/ruby/2.0.0/bundler/gems/reel-rack-a44e3629d003/lib/reel/rack/server.rb:8:in `<module:Rack>': superclass must be a Class (Module given) (TypeError)
        from /home/vagrant/wakame-dolphin/vendor/bundle/ruby/2.0.0/bundler/gems/reel-rack-a44e3629d003/lib/reel/rack/server.rb:7:in `<module:Reel>'
        from /home/vagrant/wakame-dolphin/vendor/bundle/ruby/2.0.0/bundler/gems/reel-rack-a44e3629d003/lib/reel/rack/server.rb:6:in `<top (required)>'
        from /home/vagrant/wakame-dolphin/lib/dolphin/request_handler.rb:5:in `require'
        from /home/vagrant/wakame-dolphin/lib/dolphin/request_handler.rb:5:in `<top (required)>'
        from ./bin/dolphin_server:100:in `run'
        from ./bin/dolphin_server:106:in `<main>'
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
現在のgemのバージョン一覧

``` bash
[vagrant@dolphin wakame-dolphin]$ bundle show
Gems included by the bundle:
  * actionmailer (3.2.12)
  * actionpack (3.2.12)
  * activemodel (3.2.12)
  * activesupport (3.2.12)
  * backports (3.6.0)
  * builder (3.0.4)
  * bundler (1.5.3)
  * cassandra (0.23.0)
  * celluloid (0.15.2)
  * celluloid-io (0.15.0)
  * coderay (1.1.0)
  * diff-lcs (1.2.5)
  * erubis (2.7.0)
  * extlib (0.9.16)
  * hike (1.2.3)
  * http (0.5.0)
  * http_parser.rb (0.6.0)
  * i18n (0.6.9)
  * journey (1.0.4)
  * json (1.8.1)
  * ltsv (0.1.0)
  * mail (2.4.4)
  * mail-iso-2022-jp (2.0.1)
  * method_source (0.8.2)
  * mime-types (1.25.1)
  * multi_json (1.6.1)
  * mysql2 (0.3.13)
  * nio4r (0.5.0)
  * parseconfig (1.0.2)
  * polyglot (0.3.4)
  * pry (0.9.12.6)
  * rack (1.4.5)
  * rack-cache (1.2)
  * rack-protection (1.5.2)
  * rack-test (0.6.2)
  * rake (10.0.3)
  * rb-readline (0.5.1)
  * reel (0.5.0.pre 6952a82)
  * reel-rack (0.1.0 a44e362)
  * rspec (2.13.0)
  * rspec-core (2.13.1)
  * rspec-expectations (2.13.0)
  * rspec-mocks (2.13.1)
  * sequel (4.4.0)
  * simple_uuid (0.4.0)
  * sinatra (1.4.4)
  * sinatra-contrib (1.4.2)
  * slop (3.5.0)
  * sprockets (2.2.2)
  * thrift (0.8.0)
  * thrift_client (0.8.4)
  * tilt (1.4.1)
  * timers (1.1.0)
  * treetop (1.4.15)
  * wakame-dolphin (0.0.5 df96a4f)
  * websocket_parser (0.1.6)
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
Gemfileの変更

``` bash
gem 'reel-rack', :git => 'https://github.com/axsh/reel-rack.git', :branch => 'fix-request-header', :ref => '88f2dd5a4852df573bb4f8360a0f68a6c6083a0c'
```

再度bundle install

``` bash
bundle install
```

**Comment by t-iwano** [comment]
https://github.com/axsh/reel-rack/commits/fix-request-header
エラーの原因はaxsh/reel-rackの2/14以降にかつおさんが修正した分が入るとエラーになる？
要確認。

**Comment by t-iwano** [comment]
[vagrant@dolphin wakame-dolphin]$ bundle exec ./bin/dolphin_server
I, [2014-03-18T18:59:46.693540 #28443]  INFO -- : A Reel good HTTP server! (Codename "Bette")
I, [2014-03-18T18:59:46.693668 #28443]  INFO -- : Listening on http://0.0.0.0:9004
I, [2014-03-18T18:59:46.693860 #28443]  INFO -- : [70362912300460] [Dolphin::RequestHandler] Load settings in /home/vagrant/wakame-dolphin/config/dolphin.conf
I, [2014-03-18T18:59:46.693900 #28443]  INFO -- : [70362912300460] [Dolphin::RequestHandler] Running on ruby 2.0.0 with selected Celluloid::TaskFiber
I, [2014-03-18T18:59:46.693924 #28443]  INFO -- : [70362912300460] [Dolphin::RequestHandler] Listening on http://0.0.0.0:9004

**Comment by t-iwano** [comment]
rspecテストの実行方法

``` bash
[vagrant@dolphin wakame-dolphin]$ PATH=$PATH:/home/vagrant/wakame-dolphin/ruby/bin
[vagrant@dolphin wakame-dolphin]$ ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
[vagrant@dolphin wakame-dolphin]$ bundle exec rake spec
```

**Comment by t-iwano** [comment]
mysql用config file

``` bash
[vagrant@dolphin wakame-dolphin]$ cat config/dolphin.conf
[server]
host = 0.0.0.0
port = 9004

[agent]
request_handler = 1
query_processor = 1
worker = 1
sender = 1

[database]
adapter = mysql
host = 127.0.0.1
port = 3306
user = root
pass =

[mail]
from = demo@example.com
# host = localhost
# port = 25
type = file

[logger]
format = human_readable
# format = ltsv

[template]
template_path = './spec/conf/templates/'
helper_module_path = './spec/conf/helpers/'
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
cassandraの設定
1. epelのinstall
   既にインストール済み
2. datastax.repoの作成

``` bash
[vagrant@dolphin yum.repos.d]$ sudo vi datastax.repo
[datastax]
name= DataStax Repo for Apache Cassandra
baseurl=http://rpm.datastax.com/community
enabled=1
gpgcheck=0

```

**Comment by t-iwano** [comment]
1. jre6 install

``` bash
[vagrant@dolphin yum.repos.d]$ curl -L http://javadl.sun.com/webapps/download/AutoDL?BundleId=71304 -o /tmp/jre-6u-linux-rpm.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.7M  100 19.7M    0     0  1217k      0  0:00:16  0:00:16 --:--:-- 4132k
[vagrant@dolphin yum.repos.d]$ cd /tmp
[vagrant@dolphin tmp]$ ls
jre-6u-linux-rpm.bin  ruby-build  ruby-build.20140318175639.2255.log  vagrant-shell
[vagrant@dolphin tmp]$ sh jre-6u-linux-rpm.bin
Unpacking...
Checksumming...
Extracting...
UnZipSFX 5.50 of 17 February 2002, by Info-ZIP (Zip-Bugs@lists.wku.edu).
  inflating: jre-6u38-linux-amd64.rpm
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)

Done.
[vagrant@dolphin tmp]$ sudo sh jre-6u-linux-rpm.bin
Unpacking...
Checksumming...
Extracting...
UnZipSFX 5.50 of 17 February 2002, by Info-ZIP (Zip-Bugs@lists.wku.edu).
replace jre-6u38-linux-amd64.rpm? [y]es, [n]o, [A]ll, [N]one, [r]ename: yes
  inflating: jre-6u38-linux-amd64.rpm
Preparing...                ########################################### [100%]
   1:jre                    ########################################### [100%]
Unpacking JAR files...
        rt.jar...
        jsse.jar...
        charsets.jar...
        localedata.jar...
        plugin.jar...
        javaws.jar...
        deploy.jar...

Done.
[vagrant@dolphin tmp]$ ls
hsperfdata_root  jre-6u-linux-rpm.bin  jre-6u38-linux-amd64.rpm  ruby-build  ruby-build.20140318175639.2255.log  vagrant-shell
[vagrant@dolphin tmp]$
```

**Comment by t-iwano** [comment]
sudo yum install -y http://rpm.datastax.com/community/noarch/dsc1.1-1.1.9-1.noarch.rpm

**Comment by t-iwano** [comment]
[vagrant@dolphin tmp]$ sudo alternatives --install /usr/bin/java java /usr/java/jre1.6.0_38/bin/java 20000

**Comment by t-iwano** [comment]
[vagrant@dolphin tmp]$ nodetool ring
Note: Ownership information does not include topology, please specify a keyspace.
Address         DC          Rack        Status State   Load            Owns                Token
127.0.0.1       datacenter1 rack1       Up     Normal  9.1 KB          100.00%             75406623002967053140622518166922604252
[vagrant@dolphin tmp]$

**Comment by t-iwano** [comment]
chkconfig --add cassandra

**Comment by t-iwano** [comment]
cassandraの起動

``` bash
[vagrant@dolphin tmp]$ sudo /etc/init.d/cassandra start
Starting Cassandra: OK
[vagrant@dolphin tmp]$
```

**Comment by t-iwano** [comment]
接続確認

``` bash
[vagrant@dolphin tmp]$ cassandra-cli -h 127.0.0.1
Connected to: "Test Cluster" on 127.0.0.1/9160
Welcome to Cassandra CLI version 1.1.12

Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.

[default@unknown] exit
...     ;
[vagrant@dolphin tmp]$
```

**Comment by t-iwano** [comment]
cassandra用のconfigfile

``` bash
[vagrant@dolphin config]$ sudo cp dolphin-cassandra.conf.travis dolphin.conf
[vagrant@dolphin wakame-dolphin]$ cat config/dolphin.conf
[server]
host = 0.0.0.0
port = 9004

[agent]
request_handler = 1
query_processor = 1
worker = 1
sender = 1

[database]
adapter = cassandra
hosts = 127.0.0.1
port = 9160
max_retry_count = 3
retry_interval = 3

[mail]
from = demo@example.com
# host = localhost
# port = 25
type = file

[logger]
format = human_readable
# format = ltsv

[template]
template_path = './spec/conf/templates/'
helper_module_path = './spec/conf/helpers/'
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
rake db:cassandra:migrateが動かないためrakeファイルに３行追加

``` bash
    desc 'Migrate cassandra'
    task :migrate do
      db_config = Dolphin.settings['database']
      @host = db_config['hosts'].split(',')[0]
      @port = db_config['port']
      filename = Dolphin.db_path + '/cassandra_schema.txt'
      exec "/usr/bin/cassandra-cli -h #{@host} -p #{@port} -f #{filename}"
    end
```

**Comment by t-iwano** [comment]
rake実行

``` bash
[vagrant@dolphin wakame-dolphin]$ bundle exec rake db:cassandra:migrate
Connected to: "Test Cluster" on 127.0.0.1/9160
a359fd5c-0235-3715-b9a1-fbe38da7185f
Waiting for schema agreement...
... schemas agree across the cluster
Authenticated to keyspace: dolphin
cafaa9d6-1581-3160-8966-ceaa37a05cff
Waiting for schema agreement...
... schemas agree across the cluster
d4e99858-286a-3806-a9fc-c620e4e13269
Waiting for schema agreement...
... schemas agree across the cluster
[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
rspecの失敗はテスト用のデータベースの内容が違う。

``` bash
[vagrant@dolphin wakame-dolphin]$ ls -la config/db/
total 24
drwxr-xr-x 3 vagrant vagrant 4096 Mar 18 19:42 .
drwxr-xr-x 3 vagrant vagrant 4096 Mar 18 18:23 ..
-rw-r--r-- 1 vagrant vagrant   23 Mar 18 17:50 cassandra_clear.txt
-rw-r--r-- 1 vagrant vagrant  442 Mar 18 17:50 cassandra_schema.txt
-rw-r--r-- 1 vagrant vagrant  453 Mar 18 19:42 cassandra_test_schema.txt
drwxr-xr-x 3 vagrant vagrant 4096 Mar 18 17:50 sequel
[vagrant@dolphin wakame-dolphin]$
```

rakeファイルを書き換える

``` bash
    desc 'Migrate cassandra'
    task :migrate do
      db_config = Dolphin.settings['database']
      @host = db_config['hosts'].split(',')[0]
      @port = db_config['port']
      filename = Dolphin.db_path + '/cassandra_test_schema.txt'
      exec "/usr/bin/cassandra-cli -h #{@host} -p #{@port} -f #{filename}"
    end
```

**Comment by t-iwano** [comment]
testの再実行

``` bash
[vagrant@dolphin wakame-dolphin]$ bundle exec rake spec
Finished in 16.3 seconds
32 examples, 0 failures
```

**Comment by t-iwano** [comment]
test_post_notificationのbodyの中身

``` bash
[vagrant@dolphin tests]$ ruby test_post_notification
{"email":{"to":"foo@example.com,bar@example.com","cc":"foo@example.com,bar@example.com","bcc":"foofoo@example.com,barbar@example.com"}}
```

**Comment by t-iwano** [comment]
アラートあり、ログ超過あり

curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -H "X-Message-Type: log" -X POST http://192.168.121.138:9004/events \
-d '{"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4, "limit_log":{"exceeded":1, "errors_at": ["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at": "2013-08-26T17:52:32+09:00","logs":[
{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]}'

limit_logというkeyがあると超過している
exceed:1の場合超過

アラートなし、ログ超過あり

curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -H "X-Message-Type: log" -X POST http://192.168.121.138:9004/events \
-d '{"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":0, "limit_log":{"exceeded":1, "errors_at": ["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at": "2013-08-26T17:52:32+09:00","logs":[]}'

アラートあり、ログ超過なし

curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -H "X-Message-Type: log" -X POST http://192.168.121.138:9004/events \
-d '{"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4, "limit_log":{"exceeded":0, "errors_at": []},"notified_at": "2013-08-26T17:52:32+09:00","logs":[
{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]}'

logsの中身があるかどうかがアラートがありかなしの確認方法
limit_logのexceed:0だと超過なし

eventのpostの時
curl -fsSkL -H "Content-Type: application/json" \
-H "X-Notification-ID: 10" \ 
-H "X-Message-Type: log" \
-X POST http://192.168.121.138:9004/events \

eventのgetの時
curl -fsSkL -H "Content-Type: application/json" \
-X GET http://192.168.121.138:9004/events \

notificationのpost
curl -fsSkL -H "Content-Type: application/json" \
-H "X-Notification-ID: 10" \ 
-X POST http://192.168.121.138:9004/notifications \

notificationのget
curl -fsSkL -H "Content-Type: application/json" \
-H "X-Notification-ID: 10" \
-X GET http://192.168.121.138:9004/notifications \

notificationのdelete
curl -fsSkL -H "Content-Type: application/json" \
-H "X-Notification-ID: 10" \
-X DELETE http://192.168.121.138:9004/notifications \

**Comment by t-iwano** [comment]
notification

POST

``` bash
[vagrant@dolphin tests]$  curl -fsSkL -H "Content-Type: application/json" \
> -H "X-Notification-ID: 10" \
> -X POST http://127.0.0.1:9004/notifications \
> -d '{"email":{"to":"foo@example.com,bar@example.com","cc":"foo@example.com,bar@example.com","bcc":"foofoo@example.com,barbar@example.com"}}'
{"message":"OK"}[vagrant@dolphin tests]$
```

GET

``` bash
[vagrant@dolphin tests]$  curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -X GET http://127.0.0.1:9004/notifications
{"results":{"email":{"to":"foo@example.com,bar@example.com","cc":"foo@example.com,bar@example.com","bcc":"foofoo@example.com,barbar@example.com"}},"message":"OK"}[vagrant@dolphin tests]$
```

DELETE

``` bash
[vagrant@dolphin tests]$ curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -X DELETE http://127.0.0.1:9004/notifications
{"message":"OK"}[vagrant@dolphin tests]$
```

DELETE後GET

``` bash
[vagrant@dolphin tests]$  curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -X GET http://127.0.0.1:9004/notifications                             curl: (22) The requested URL returned error: 404 Not Found
[vagrant@dolphin tests]$
```

**Comment by t-iwano** [comment]
events

POST

``` bash
[vagrant@dolphin wakame-dolphin]$  curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -H "X-Message-Type: log" -X POST http://127.0.0.1:9004/events -d '{"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4, "limit_log":{"exceeded":1, "errors_at": ["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at": "2013-08-26T17:52:32+09:00","logs":[
{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]}'
{"message":"OK"}[vagrant@dolphin wakame-dolphin]$
```

GET

``` bash
[vagrant@dolphin wakame-dolphin]$ curl -fsSkL -H "Content-Type: application/json" -H "X-Notification-ID: 10" -H "X-Message-Type: log" -X GET http://127.0.0.1:9004/events
{"results":[{"id":"a2e1f032-ae88-11e3-90f2-7ae76d29f153","event":{"notification_id":"test","message_type":"default","messages":{"message":"Alert!!!!"}},"created_at":"2014-03-18T19:32:42+09:00"},{"id":"b77626d0-ae88-11e3-8909-14cdf623fd2f","event":{"notification_id":"test","message_type":"default","messages":{"message":"Alert!!!!"}},"created_at":"2014-03-18T19:33:16+09:00"},{"id":"b78e61d2-ae88-11e3-81c3-c01a30412934","event":{"subject":"subject","body":"body","message":"Alert!!!!"},"created_at":"2014-03-18T19:33:16+09:00"},{"id":"b80a19bc-ae88-11e3-84e3-3b96173df174","event":{"message":"Alert!!!!"},"created_at":"2014-03-18T19:33:17+09:00"},{"id":"42ef9646-ae8a-11e3-8a2f-bbd7e9678c21","event":{"notification_id":"test","message_type":"default","messages":{"message":"Alert!!!!"}},"created_at":"2014-03-18T19:44:20+09:00"},{"id":"42fab63e-ae8a-11e3-9654-8dbf0ab4e76b","event":{"subject":"subject","body":"body","message":"Alert!!!!"},"created_at":"2014-03-18T19:44:20+09:00"},{"id":"433b7c78-ae8a-11e3-96e0-054b03af3d6e","event":{"message":"Alert!!!!"},"created_at":"2014-03-18T19:44:20+09:00"},{"id":"15e16b14-ae8c-11e3-896d-b1b20650910f","event":{"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4,"limit_log":{"exceeded":1,"errors_at":["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at":"2013-08-26T17:52:32+09:00","logs":[{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]},"created_at":"2014-03-18T19:57:23+09:00"},{"id":"4910da60-ae8c-11e3-896b-eb008a4640b8","event":{"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4,"limit_log":{"exceeded":1,"errors_at":["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at":"2013-08-26T17:52:32+09:00","logs":[{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]},"created_at":"2014-03-18T19:58:49+09:00"}],"message":"OK"}[vagrant@dolphin wakame-dolphin]$
```

**Comment by t-iwano** [comment]
[vagrant@dolphin wakame-dolphin]$ cassandra-cli -h 127.0.0.1
Connected to: "Test Cluster" on 127.0.0.1/9160
Welcome to Cassandra CLI version 1.1.12

Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.

[default@unknown] quit;
[vagrant@dolphin wakame-dolphin]$ cassandra-cli -h 127.0.0.1 -k dolphin
Connected to: "Test Cluster" on 127.0.0.1/9160
Welcome to Cassandra CLI version 1.1.12

Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.

[default@dolphin] quit;
[vagrant@dolphin wakame-dolphin]$ cassandra-cli -h 127.0.0.1
Connected to: "Test Cluster" on 127.0.0.1/9160
Welcome to Cassandra CLI version 1.1.12

Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.

[default@unknown] use dolphin
...     ;
Authenticated to keyspace: dolphin
[default@dolphin]

**Comment by t-iwano** [comment]
[default@dolphin] ?;
Getting around:
?                       Display this help.
help;                   Display this help.
help <command>;         Display command-specific help.
exit;                   Exit this utility.
quit;                   Exit this utility.

Commands:
assume                  Apply client side validation.
connect                 Connect to a Cassandra node.
consistencylevel        Sets consisteny level for the client to use.
count                   Count columns or super columns.
create column family    Add a column family to an existing keyspace.
create keyspace         Add a keyspace to the cluster.
del                     Delete a column, super column or row.
decr                    Decrements a counter column.
describe cluster        Describe the cluster configuration.
describe                Describe a keyspace and its column families or column family in current keyspace.
drop column family      Remove a column family and its data.
drop keyspace           Remove a keyspace and its data.
drop index              Remove an existing index from specific column.
get                     Get rows and columns.
incr                    Increments a counter column.
list                    List rows in a column family.
set                     Set columns.
show api version        Show the server API version.
show cluster name       Show the cluster name.
show keyspaces          Show all keyspaces and their column families.
show schema             Show a cli script to create keyspaces and column families.
truncate                Drop the data in a column family.
update column family    Update the settings for a column family.
update keyspace         Update the settings for a keyspace.
use                     Switch to a keyspace.

[default@dolphin]

**Comment by t-iwano** [comment]
``` bash
[default@dolphin] list notifications;
Using default limit of 100
Using default column limit of 100
-------------------
RowKey: test
=> (column=methods, value={"email":{"to":"test_to@example.com"}}, timestamp=1395139460290669)
-------------------
RowKey: 10
=> (column=methods, value={"email":{"to":"foo@example.com,bar@example.com","cc":"foo@example.com,bar@example.com","bcc":"foofoo@example.com,barbar@example.com"}}, timestamp=1395140135399103)
-------------------
RowKey: system

3 Rows Returned.
Elapsed time: 43 msec(s).
[default@dolphin]
```

**Comment by t-iwano** [comment]
``` bash
[default@dolphin] list events;
Using default limit of 100
Using default column limit of 100
-------------------
RowKey: history
=> (column=a2e1f032-ae88-11e3-90f2-7ae76d29f153, value={"notification_id":"test","message_type":"default","messages":{"message":"Alert!!!!"}}, timestamp=1395138762275313)
=> (column=b77626d0-ae88-11e3-8909-14cdf623fd2f, value={"notification_id":"test","message_type":"default","messages":{"message":"Alert!!!!"}}, timestamp=1395138796800710)
=> (column=b78e61d2-ae88-11e3-81c3-c01a30412934, value={"subject":"subject","body":"body","message":"Alert!!!!"}, timestamp=1395138796960525)
=> (column=b80a19bc-ae88-11e3-84e3-3b96173df174, value={"message":"Alert!!!!"}, timestamp=1395138797771114)
=> (column=42ef9646-ae8a-11e3-8a2f-bbd7e9678c21, value={"notification_id":"test","message_type":"default","messages":{"message":"Alert!!!!"}}, timestamp=1395139460296695)
=> (column=42fab63e-ae8a-11e3-9654-8dbf0ab4e76b, value={"subject":"subject","body":"body","message":"Alert!!!!"}, timestamp=1395139460370371)
=> (column=433b7c78-ae8a-11e3-96e0-054b03af3d6e, value={"message":"Alert!!!!"}, timestamp=1395139460794875)
=> (column=15e16b14-ae8c-11e3-896d-b1b20650910f, value={"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4,"limit_log":{"exceeded":1,"errors_at":["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at":"2013-08-26T17:52:32+09:00","logs":[{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]}, timestamp=1395140243700450)
=> (column=4910da60-ae8c-11e3-896b-eb008a4640b8, value={"alert_engine":"fluentd","state":"alarm","alarm_id":"alm-rtut8p8q","metric_name":"log","resource_id":"i-vqkwlpai","ipaddr":"192.168.0.1","match_value":"td-agent","tag":"var.log.messages","display_name":"Syslog Alert","match_count":4,"limit_log":{"exceeded":1,"errors_at":["2013-08-13T16:08:15+09:00","2013-08-13T16:08:16+09:00","2013-08-13T16:08:17+09:00"]},"notified_at":"2013-08-26T17:52:32+09:00","logs":[{"evaluated_value":"mysql\napache\ntd-agent","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:15+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:17+09:00"},{"evaluated_value":"td-agent\napache\nmysql","evaluated_at":"2013-08-13T16:08:18+09:00"}]}, timestamp=1395140329575339)

1 Row Returned.
Elapsed time: 11 msec(s).
[default@dolphin]
```
